const CLICK_VOLUME = 0.2;

const BULLET_SPEED = 20;
const WEAPON_OFFSET = {
  x: -0.2,
  y: 1.9,
  z: 0.8,
};
const SPECIAL_OBSTACLE_PERCENTAGE_TO_APPEAR = 35;
const OBSTACLE_VELOCITY = 8;
const OBSTACLE_HEALTH_MULTIPLY_FACTOR = 5;
const OBSTACLE_HEALTH_STANDARD_HEALTH = 2;

const HITTED_OBSTACLE_SOUND_VOLUME = 0.8;
const GAME_OVER_VOLUME = 0.5;
const GUN_SHOOT_VOLUME = 0.5;

const PLAYER_CONTROLLER = {
  FIRE_RATE: 400,
  MOVEMENT_SPEED: 0.5,
  MAX_VEL: 3,
};

export {
  BULLET_SPEED,
  SPECIAL_OBSTACLE_PERCENTAGE_TO_APPEAR,
  GUN_SHOOT_VOLUME,
  HITTED_OBSTACLE_SOUND_VOLUME,
  OBSTACLE_VELOCITY,
  PLAYER_CONTROLLER,
  WEAPON_OFFSET,
  OBSTACLE_HEALTH_MULTIPLY_FACTOR,
  OBSTACLE_HEALTH_STANDARD_HEALTH,
  CLICK_VOLUME,
  GAME_OVER_VOLUME,
};
